### ISSUE TITLE
Intent doesn't capture "what version are you?"

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/skill-version-checker#30]
Captures, "what version are you *running*?" but not the issue title. Thought that was odd.

**Comment by krisgesling** [comment]
The intent matches on vocab of "Check" + "version".

[`check.voc`](https://github.com/MycroftAI/skill-version-checker/blob/19.08/vocab/en-us/Check.voc) contains "what is" instead of just "what".

Can anyone see a reason not to reduce this to just "what"?
