### ISSUE TITLE
Offer to upgrade?

### ISSUE THREAD

**Issue by itsholton** [MycroftAI/skill-version-checker#8]
If your version checker finds we need upgrades, can you ask, "Do you want me to upgrade?"
Maybe it is not too much?  Not sure, but thanks for looking into it...

**Comment by KathyReid** [comment]
From a usability point of view, I *really* like this idea. Mycroft should check every hour to see if there's an update available, but this could then attempt to install an upgrade, and could add troubleshooting information, in case a device is "stuck" and not upgrading.
